version: "3.8"

services:

  app_proxy:
    environment:
      APP_HOST: wvk2017-fractal-bitcoin-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: wvk2017/nodes:fractal-bitcoin
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.fractal-bitcoin:/root/.fractal-bitcoin
    ports:
      - 9030:9030    # RPC
      - 7030:7030    # ZMQ
    entrypoint: "bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7030 -rpcbind=0.0.0.0 -rpcport=9030 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
