version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: wvk2017-miningcore-webui_web_1
      APP_PORT: 8080
  web:
    image: wvk2017/Miningcore.WebUI
#    ports:
#      - 5002:8080
    restart: on-failure
    volumes:
      - /home/umbrel/.miningcore:/app/Miningcore.WebUI
    user: "1000:1000"
    environment:
      - POOL_NAME=Self-Hosted Mining Pool
      - STRATUM_HOST=umbrel.local
      - API_BASE_URL=http://wvk2017-miningcore_server_1:4000/api
      - PLATFORM=UMBREL 
